USE `fishing-ecommerce`;

CREATE TABLE IF NOT EXISTS users(
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(300) NOT NULL,
	`email` VARCHAR(300) NOT NULL,
    `password` VARCHAR(400) NOT NULL,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tokens(
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `value` VARCHAR(300) NOT NULL,
    `expiry` DATETIME NOT NULL,
    `user_id` INT NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES users (`id`)
);

CREATE TABLE IF NOT EXISTS products(
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(300) NOT NULL,
    `description` VARCHAR(500) NOT NULL,
    `value` VARCHAR(10) NOT NULL,
    `amount` INT NOT NULL,
    `img_path` LONGBLOB NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
DELIMITER //
CREATE TRIGGER IF NOT EXISTS expiry_insert_tokens
BEFORE INSERT ON tokens
FOR EACH ROW
BEGIN
    SET NEW.expiry = DATE_ADD(NOW(), INTERVAL 1 DAY);
END;
//
DELIMITER ;