CREATE DATABASE `fishing-ecommerce`;
USE `fishing-ecommerce`;

CREATE TABLE users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(300) NOT NULL,
	email VARCHAR(300) NOT NULL,
    password VARCHAR(400) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tokens(
    id INT AUTO_INCREMENT PRIMARY KEY,
    value VARCHAR(300) NOT NULL,
    expiry DATETIME DEFAULT DATE_ADD(CURRENT_TIME, INTERVAL 1 DAY),
    user_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id)
);