version: '3.7'
services:
  database:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 2b2232df-eb16-432f-a9f7-1242f3fa54b4
      MYSQL_DATABASE: fishing-ecommerce
    ports:
      - "3306:3306"
    volumes:
      - ./app/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  web:
    build:
      context: ./
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy

  phpmyadmin:
    container_name: php_my_admin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: 2b2232df-eb16-432f-a9f7-1242f3fa54b4
    depends_on:
      database:
        condition: service_healthy
